image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service

cache:
  paths:
    - node_modules/

stages:
  - init
  - deploy

Init:
  when: always
  stage: init
  services:
  - postgres:latest
  variables:
    POSTGRES_DB: nice_marmot
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - npm i
    - npm run eslint
    - npm run start

Deploy:
  when: manual
  stage: deploy
  script:
    # - echo "DB_NAME=$DB_NAME" > .env
    # - echo "DB_USER=$DB_USER" > .env
    # - echo "DB_HOST=$DB_HOST" > .env
    # - echo "DB_PASS=$DB_PASS" > .env
    - npm install -g serverless
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
    - serverless deploy
  only:
    - master




